# Generated by Django 5.0.7 on 2024-08-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otp_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_active",
        ),
    ]
