# Generated by Django 5.0.7 on 2024-08-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_otp_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
