# Generated by Django 5.0.7 on 2024-08-07 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HoroscopeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("sunshine", "Sunshine"),
                            ("love", "Love"),
                            ("career", "Career"),
                            ("money", "Money"),
                            ("health", "Health"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HoroscopeSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("aries", "Aries"),
                            ("taurus", "Taurus"),
                            ("gemini", "Gemini"),
                            ("cancer", "Cancer"),
                            ("leo", "Leo"),
                            ("virgo", "Virgo"),
                            ("libra", "Libra"),
                            ("scorpio", "Scorpio"),
                            ("sagittarius", "Sagittarius"),
                            ("capricorn", "Capricorn"),
                            ("aquarius", "Aquarius"),
                            ("pisces", "Pisces"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HoroscopeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
                ("sex_rating", models.IntegerField(default=0)),
                ("hustle_rating", models.IntegerField(default=0)),
                ("vibe_rating", models.IntegerField(default=0)),
                ("success_rating", models.IntegerField(default=0)),
                ("mood_emoji", models.CharField(blank=True, max_length=5)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horoscopes.horoscopecategory",
                    ),
                ),
                (
                    "career_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_matches",
                        to="horoscopes.horoscopesign",
                    ),
                ),
                (
                    "friendship_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_matches",
                        to="horoscopes.horoscopesign",
                    ),
                ),
                (
                    "love_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="love_matches",
                        to="horoscopes.horoscopesign",
                    ),
                ),
                (
                    "sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horoscopes.horoscopesign",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horoscopes.horoscopetype",
                    ),
                ),
            ],
        ),
    ]
