# Generated by Django 5.0.7 on 2024-08-07 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horoscopes", "0002_remove_horoscope_date_horoscope_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horoscope",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="horoscope",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
